INSERT INTO Gebruiker (id, voornaam, achternaam, email, wachtwoord, favorieteProgrammeertaal) VALUES (1, 'Frits','Spits','frits@spits.nl','welkom','java')
INSERT INTO Gebruiker (id, voornaam, achternaam, email, wachtwoord, favorieteProgrammeertaal) VALUES (2, 'Ruud', 'Gullit', 'ruud@gullit.nl', 'welkom', 'python');
INSERT INTO Gebruiker (id, voornaam, achternaam, email, wachtwoord, favorieteProgrammeertaal) VALUES (3, 'Klaas', 'Knot', 'klaas@knot.nl', 'welkom', 'C++');
INSERT INTO Categorie (id, naam, parent_id) VALUES (1, 'kite surf', null);
INSERT INTO Categorie (id, naam, parent_id) VALUES (2, 'kites', 1);
INSERT INTO Categorie (id, naam, parent_id) VALUES (3, 'kite boards', 1);
INSERT INTO Categorie (id, naam, parent_id) VALUES (4, 'kites 7m', 2);
INSERT INTO Categorie (id, naam, parent_id) VALUES (5, 'kites 9m', 2);
INSERT INTO Categorie (id, naam, parent_id) VALUES (6, 'kites 11m', 2);
INSERT INTO Categorie (id, naam, parent_id) VALUES (7, 'gereedschap', null);
INSERT INTO Categorie (id, naam, parent_id) VALUES (8, 'schroevendraaiers', 7);
INSERT INTO Categorie (id, naam, parent_id) VALUES (9, 'kwasten', 7);
INSERT INTO Categorie (id, naam, parent_id) VALUES (10, 'doppenset', 7);
INSERT INTO Categorie (id, naam, parent_id) VALUES (11, 'boormachine', 7);
INSERT INTO Categorie (id, naam, parent_id) VALUES (12, 'fietsen', null);
INSERT INTO Categorie (id, naam, parent_id) VALUES (13, 'elektrische fietsen', 12);
INSERT INTO Categorie (id, naam, parent_id) VALUES (14, 'race fietsen', 12);
INSERT INTO Categorie (id, naam, parent_id) VALUES (15, 'stad fietsen', 12);
INSERT INTO Categorie (id, naam, parent_id) VALUES (16, 'speed pedelec', 13);
INSERT INTO Advertentie  (id, titel, soort, vraagprijs, omschrijving, categorie_id, aanbieder_id) VALUES (1, 'kite North 9m', 'PRODUCT', '500,-', 'north kite nooit gebruikt',5 , 1);
INSERT INTO Advertentie  (id, titel, soort, vraagprijs, omschrijving, categorie_id, aanbieder_id) VALUES (2, 'kite board geel', 'PRODUCT', '100,-', 'f1 kite board zo goed als nieuw',3, 2);
INSERT INTO Advertentie  (id, titel, soort, vraagprijs, omschrijving, categorie_id, aanbieder_id) VALUES (3, 'kite North 11m', 'PRODUCT', '300,-', 'north kite 11m geel',6, 3);
INSERT INTO Advertentie  (id, titel, soort, vraagprijs, omschrijving, categorie_id, aanbieder_id) VALUES (4, 'kite North 7m', 'PRODUCT', '1.000,-', 'mooie kite in goede staat',4 , 1);
INSERT INTO Advertentie  (id, titel, soort, vraagprijs, omschrijving, categorie_id, aanbieder_id) VALUES (5, 'kite board groen', 'PRODUCT', '150,-', 'slingshot kite board ',3, 2);
INSERT INTO Advertentie  (id, titel, soort, vraagprijs, omschrijving, categorie_id, aanbieder_id) VALUES (6, 'oude race fiets','PRODUCT', '75,-', 'vintage peugeot fiets',14, 3);
INSERT INTO Advertentie  (id, titel, soort, vraagprijs, omschrijving, categorie_id, aanbieder_id) VALUES (7, 'elektrische gazelle','PRODUCT', '3.000,-', 'top ding',13, 3);
INSERT INTO Advertentie  (id, titel, soort, vraagprijs, omschrijving, categorie_id, aanbieder_id) VALUES (8, 'verf kwasten', 'PRODUCT', 'gratis', 'gratis ophalen',9, 3);
INSERT INTO Advertentie  (id, titel, soort, vraagprijs, omschrijving, categorie_id, aanbieder_id) VALUES (9, 'Makita accu 18v','PRODUCT', 'bieden', 'kan verstuurd worden',11, 3);